login_register/urls.py
from django.urls import path
from . import views

app_name = 'login_register'

urlpatterns = [
  path('register/', views.registerPage, name="register"),
  path('login/', views.loginPage, name="login"),
  path('logout/', views.logoutUser, name="logout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('igclone.urls')),
    path('', include('reset_password.urls')),
    path('', include('login_register.urls')),
    path(
    "favicon.ico",
    RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
),
]

urlpatterns += static(settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT)

login_register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
  password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
  password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
  class Meta:
    model = User
    fields = ['username', 'first_name', 'email', 'password1', 'password2',]
    widgets = {
      'username':forms.TextInput(attrs={'placeholder': 'Username'}),
      'first_name':forms.TextInput(attrs={'placeholder': 'Full Name'}),
      'email':forms.EmailInput(attrs={'placeholder': 'Email'}),
    }

login_register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import CreateUserForm
from .decorators import unauthenticated_user


@unauthenticated_user
def registerPage(request):
  form = CreateUserForm()
  if request.method == 'POST':
    form = CreateUserForm(request.POST)
    if form.is_valid():
      form.save()
      print('USER_CREATED: ', form.cleaned_data.get('username'))

      username = form.cleaned_data.get('username')
      messages.success(request, 'Account was created for ' + username)
      return redirect('login_register:login')

  context = {'form':form}
  return render(request, 'login_register/register.html', context)


@unauthenticated_user
def loginPage(request):
  
  if request.method == 'POST':
    print('LOGIN: ',request.POST)
    username = request.POST.get('username').lower()
    password = request.POST.get('password')

    user = authenticate(request, username=username, password=password)
    
    if user is not None:
      login(request, user)
      print('LOGGEDIN: ', user)
      return redirect("user_page", user.id)
    else:
      messages.info(request, 'Username OR Password is incorrect')

  return render(request, 'login_register/login.html')


def logoutUser(request):
  logout(request)
  return redirect('login_register:login')

login_register/templates/login_register/login.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}  
  <!-- Login CSS -->
  <link rel="stylesheet" href="{% static 'css/login_pag.css' %}">

  <!-- Main Container -->
  <div class="l_wrapper">

    <div class="container flex">

      <!-- First Flex Item -->
      <i class="fab fa-instagram fa-10x"></i>

      <!-- Second Flex Item -->
      <!-- Flex Container -->
      <div class="login_container">

        <p>If don't want to create a new user just</p>
        <p>use the following credentials below</p>
        <div class="doe"><p>Username:</p><p id="john">John</p></div>
        <div class="doe"><p>Password:</p><p id="john">will1111</p></div>
        

        <!-- Form Card -->
        <div class="card">
          <img class="instagram_logo" src="{% static 'images/instagram_logo.png' %}" alt="">
          <form method="POST" action="" class="">
            {% csrf_token %}
            <div class="form_control">
              <input type="text" name="username" placeholder="Username" required>
            </div>
            <div class="form_control">
              <input type="text" name="password" placeholder="Password" required>
            </div>
            {% for message in messages %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              <div class="l_error">{{message}}</div>
              {% else %}
              <div style="color:green;" class="l_error">{{message}}</div>
              {% endif %}
            {% endfor %}
            <input type="submit" value="Log In" class="btn">
            <a href="{% url 'reset_password' %}" class="l_password_reset">Forgot password?</a>
          </form>
        </div>
        <!-- Sign Up Card -->
        <div class="signup_card card">Don't have an account?&nbsp;<a href="{% url 'login_register:register' %}">Sign up</a>
        </div>

        <p>Get the app.</p>
        
        <div class="l_download_icons">
          <a href="https://play.google.com/">
          <img class="l_icon" src="{% static 'images/googleplay.png' %}"></a>
                
          <a href="https://apps.apple.com/">
          <img class="l_icon" src="{% static 'images/appstore.png' %}"></a>
        </div>
        
      </div>
      
    </div>

  </div>

{% endblock content %}

login_register/templates/login_register/register.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Sign up{% endblock title %}
{% block content %}

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/register_page.css' %}">

  <!-- Register Form -->
  <div class="r_wrapper">
    <div class="container flex">
      <!-- Form Card -->
      <div class="card">
        <img class="instagram_logo" src="{% static 'images/instagram_logo.png' %}" alt="">
        <div class="sec_header">Sign up to see photos and videos from your friends.</div> 
        <form method="POST" action="" class="">
          {% csrf_token %}
          <div class="form_control">
            {{form.username}}
          </div>
          <div class="form_control">
            {{form.first_name}}
          </div>
          <div class="form_control">
            {{form.email}}
          </div>
          <div class="form_control">
            {{form.password1}}
          </div>
          <div class="form_control">
            {{form.password2}}
          </div>  
          <input type="submit" value="Sign up" class="btn">
          <div class="sec_header r_policy">By signing up, you agree to our Terms , Data Policy and Cookies Policy.</div>
        </form>
      </div>

      <!-- Error Message -->
      <div class="l_error">{{form.errors}}</div>

      <!-- Sign Up Card -->
      <div class="signup_card card">Have an account?&nbsp;<a href="{% url 'login_register:login' %}">Log In</a>
      </div>

      <p>Get the app.</p>
      
      <div class="l_download_icons">
        <a href="https://play.google.com/">
        <img class="l_icon" src="{% static 'images/googleplay.png' %}"></a>
              
        <a href="https://apps.apple.com/">
        <img class="l_icon" src="{% static 'images/appstore.png' %}"></a>
      </div>

    </div>
  </div>

{% endblock content %}