igclone/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.index, name="home"),
  path('user_page/<int:pk>/', views.userPage, name="user_page"),
  path('add_photo/', views.add_photo, name="add_photo"),
  path('edit_profile/<int:pk>/', views.edit_profile, name="edit_profile"),
  path('delete_profile/<int:pk>/', views.delete_profile, name="delete_profile"),
  path('follow_user/<int:pk>/', views.follow_user, name="follow_user"),
  path('post/<int:pk>/', views.post_user, name="post"),
  path('delete_post/<int:pk>/', views.delete_post, name="delete_post"),
  path('user_page/<int:pk>/following/', views.followingPage, name="following"),
  path('user_page/<int:pk>/followers/', views.followersPage, name="followers"),
  path('following-list/<int:pk>/', views.followingList, name="followingList"),
  path('follower-list/<int:pk>/', views.followerList, name="followerList"),
  path('user_page/<int:u_pk>/publication/<int:p_pk>/', views.publicationDetail, name="publication"),
]

login_register/urls.py
from django.urls import path
from . import views

app_name = 'login_register'

urlpatterns = [
  path('register/', views.registerPage, name="register"),
  path('login/', views.loginPage, name="login"),
  path('logout/', views.logoutUser, name="logout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('igclone.urls')),
    path('', include('reset_password.urls')),
    path('', include('login_register.urls')),
    path(
    "favicon.ico",
    RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
),
]

urlpatterns += static(settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT)

igclone/models.py
from django.db import models
from django.contrib.auth.models import User


class InstagramUser(models.Model):
  user = models.OneToOneField(User, blank=True, on_delete=models.CASCADE, primary_key=True)
  profile_pic = models.ImageField(default='default_user_icon.png', null=True, blank=True)
  follower = models.ManyToManyField(User, related_name='follower', default=None, blank=True)
  following = models.ManyToManyField(User, related_name='following', default=None, blank=True)
  date_created = models.DateTimeField(auto_now_add=True, null=True)

  def __str__(self):
    return self.user.username

  @property
  def followers(self):
    return self.follower.all().count()

  @property
  def followings(self):
    return self.following.all().count()


class Publication(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
  liked = models.ManyToManyField(User, related_name='publication_like', default=None, blank=True)
  pub_date = models.DateTimeField(auto_now_add=True, null=True)
  image = models.ImageField(null=True, blank=True)
  description = models.CharField(max_length=200, null=True, blank=True)

  def __str__(self):
    return self.description

  @property
  def likes(self):
    return self.liked.all().count()


class SwitchTheme(models.Model):
  user = models.OneToOneField(InstagramUser, blank=True, on_delete=models.CASCADE, primary_key=True)
  theme = models.CharField(default='https://timbucketaws.s3.amazonaws.com/static/css/main.css', max_length=200, null=True, blank=True)

  def __str__(self):
    return self.theme


class Comment(models.Model):
  publication = models.ForeignKey(Publication, related_name='comments', blank=True, on_delete=models.CASCADE)
  author = models.CharField(max_length=200, null=True, blank=True)
  body = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True, null=True)

  def __str__(self):
    return '%s - %s - %s' % (self.author, self.publication.description, self.body[:20])

igclone/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms

from .models import InstagramUser, Publication


class InstagramUserForm(ModelForm):
  profile_pic = forms.ImageField(widget=forms.FileInput)
  class Meta:
    model = InstagramUser
    fields = ['profile_pic']


class UpdateUserForm(ModelForm):
  class Meta:
    model = User
    fields = ['username', 'first_name']


class UpdatePublicationForm(ModelForm):
  image = forms.ImageField(widget=forms.FileInput)
  class Meta:
    model = Publication
    fields = ['image', 'description']

igclone/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Publication, Comment
from .forms import UpdateUserForm, InstagramUserForm, UpdatePublicationForm
from .serializers import PublicationSerializer, SwitchThemeSerializer, CommentSerializer
from .filters import FollowingFilter, FollowerFilter


@login_required(login_url='login_register:login')
@api_view(['GET', 'POST'])
def index(request):
  brad = User.objects.get(id=36)
  print("BRAD: ", brad.id)
  # The logged in user
  user = request.user
  # Get all publications of the logged user
  user_pubs = user.publication_set.all()
  # Get all users whom the logged in user follows to
  following_users = user.instagramuser.following.all()

  # Get all Publications that the logged in user can see
  pub_list = []
  for following_user in following_users:
    pub_list += following_user.publication_set.all()
  pub_list.extend(user_pubs)

  # Sort Publications by created date
  following_pub_list = sorted(pub_list, reverse=True, key=lambda obj: obj.pub_date)

  # Like/Unlike Handler
  if request.is_ajax():
    # if request.POST.get('like') == 'like':
      publication_id = request.POST.get('publication_id')
      publication = Publication.objects.get(id=publication_id)
      if user not in publication.liked.all():
        publication.liked.add(user)
      else:
        publication.liked.remove(user)
      pub_serializer = PublicationSerializer(publication, many=False)
      return JsonResponse({"likes_number":publication.likes, 'user_id':user.id, "pub_liked":pub_serializer.data}, status=200)

  # Suggested list
  all_users = User.objects.all()
  suggestioned_users = []
  for suggestioned_user in all_users:
    if user not in suggestioned_user.instagramuser.follower.all():
      suggestioned_users.append(suggestioned_user)
    else:
      pass

  suggestioned_users.remove(user)
  suggestioned_list = sorted(suggestioned_users, reverse=True, key=lambda obj: obj.instagramuser.followers)

  # 
  # Comment Section
  # 
  
  # check if Fetch API call
  if request.headers.get('content-type') == 'application/json':

    # get 'comment text' from fetch
    comment_text = request.data['comment_text']
    
    # get Publication Id from fetch
    pub_id = request.data['id_publication']

    # Publication
    pub = Publication.objects.get(id=pub_id)
    
    # Author of Comment
    author_name = user.first_name
    
    # check if Comment Text is not empty
    if comment_text != '':
      
      # creating a new comment
      new_comment = Comment.objects.create(publication=pub, author=author_name, body=comment_text)
      # saving a new comment
      new_comment.save()

      # 3 last comments of publication in a reversed order, (the newest on top)
      comments = pub.comments.all().order_by('-date_added')[:3]

      # serializing comments
      comm_serializer = CommentSerializer(comments, many=True)

      return Response(comm_serializer.data)
      
    else:
      pass

  context = {'user':user, 'publications':following_pub_list, 'suggestioned_users':suggestioned_list[:5]}
  return render(request, 'igclone/index.html', context)


@login_required(login_url='login_register:login')
@api_view(['GET'])
def userPage(request, pk):    
  user = User.objects.get(id=pk)
  switch_theme = user.instagramuser.switchtheme

  if request.headers.get('content-type') == 'application/json':
    serializer = SwitchThemeSerializer(switch_theme)
    return Response(serializer.data)

  user_attributes = user.publication_set.order_by('-pub_date').all()
  num_user_photos = user_attributes.count()
  num_followers = user.instagramuser.followers
  num_following = user.instagramuser.followings
  context = {'user':user, 'user_attributes':user_attributes, 'num_user_photos':num_user_photos, 'num_followers':num_followers, 'num_following':num_following}

  return render(request, 'igclone/user_page.html', context)


@login_required(login_url='login_register:login')
def publicationDetail(request, u_pk, p_pk):

  # user = request.user
  post = Publication.objects.get(id=p_pk)
  likes = post.likes
  liked_list = post.liked.all()
  print("LIKE LIST: ", post.liked.all())
  comments = post.comments.all()
  num_comments = post.comments.all().count()
  # context = {'post':post, 'form_post':form_post}
  context = {'post':post, 'likes':likes, 'liked_list':liked_list, 'comments':comments, 'num_comments':num_comments}
  return render(request, 'igclone/publication.html', context)


@login_required(login_url='login_register:login')
def add_photo(request):

  user = request.user

  if request.method == 'POST':
    image = request.FILES.get('pub_img')
    description = request.POST.get('descrip')

    publication = Publication(user=user, image=image, description=description)
    publication.save()

    return redirect('user_page', user.pk)

  return render(request, 'igclone/add_photo.html')


@login_required(login_url='login_register:login')
@api_view(['GET', 'POST'])
def edit_profile(request, pk):

  user = User.objects.get(id=pk)
  instagramuser = user.instagramuser
  form = UpdateUserForm(instance=user)
  profile_pic_form = InstagramUserForm(instance=instagramuser)

  # check if it's an API call. and if it is then swap the theme to the opposite one
  if request.headers.get('content-type') == 'application/json':
    # get user's id that fetch API provides from edit_profile.js
    data = request.data['user']
    # query user
    api_user = User.objects.get(id=data)

    # swaping theme
    if api_user.instagramuser.switchtheme.theme == 'https://timbucketaws.s3.amazonaws.com/static/css/main.css':
      api_user.instagramuser.switchtheme.theme = 'https://timbucketaws.s3.amazonaws.com/static/css/swap_color.css'
      api_user.instagramuser.switchtheme.save()
    else:
      api_user.instagramuser.switchtheme.theme = 'https://timbucketaws.s3.amazonaws.com/static/css/main.css'
      api_user.instagramuser.switchtheme.save()
    theme = api_user.instagramuser.switchtheme

    # serializering a SwitchTheme model
    serializer = SwitchThemeSerializer(theme)
    return Response(serializer.data)

  # Update user's information
  if request.POST.get('update') == 'update':    
    profile_pic_form = InstagramUserForm(request.POST, request.FILES, instance=instagramuser)
    form = UpdateUserForm(request.POST, instance=user)
    if form.is_valid() and profile_pic_form.is_valid():
      form.save() and profile_pic_form.save()
    return redirect('edit_profile', user.id)

  context = {'form':form, 'pic_form':profile_pic_form}

  return render(request, 'igclone/edit_profile.html', context)


@login_required(login_url='login_register:login')
def delete_profile(request, pk):
  user = User.objects.get(id=pk)
  if request.method == 'POST':
    user.delete()
    return redirect('login_register:login')
  context = {'user':user}
  return render(request, 'igclone/delete_profile.html', context)


@login_required(login_url='login_register:login')
def follow_user(request, pk):
  guest_user = request.user
  host_user = User.objects.get(id=pk)
  
  if request.method == 'POST':
    if host_user not in guest_user.instagramuser.following.all():
      guest_user.instagramuser.following.add(host_user)
      host_user.instagramuser.follower.add(guest_user)
    else:
      guest_user.instagramuser.following.remove(host_user)
      host_user.instagramuser.follower.remove(guest_user)
    return redirect('follow_user', host_user.id)

  users_photos = host_user.publication_set.order_by('-pub_date').all()
  num_users_photos = users_photos.count()

  num_followers = host_user.instagramuser.followers
  num_following = host_user.instagramuser.followings

  context = {'host_user':host_user, 'guest_user':guest_user, 'users_photos':users_photos, 'num_users_photos':num_users_photos, 'num_followers':num_followers, 'num_following':num_following}
  return render(request, 'igclone/follow_user.html', context)


@login_required(login_url='login_register:login')
def post_user(request, pk):
  user = request.user
  post = Publication.objects.get(id=pk)
  form_post = UpdatePublicationForm(instance=post)
  if request.method == 'POST':
    form_post = UpdatePublicationForm(request.POST, request.FILES, instance=post)
    if form_post.is_valid:
      form_post.save()
    return redirect('user_page', user.id)
  context = {'post':post, 'form_post':form_post}
  return render(request, 'igclone/post_user.html', context)


@login_required(login_url='login_register:login')
def delete_post(request, pk):
  user = request.user
  post = Publication.objects.get(id=pk)
  if request.method == 'POST':
    post.delete()
    return redirect('user_page', user.id)
  context = {'post':post}
  return render(request, 'igclone/delete_post.html', context)


@login_required(login_url='login_register:login')
def followingPage(request, pk):
  user = request.user
  following_list = user.instagramuser.following.all()
  following_filter = FollowingFilter(request.GET, queryset=following_list)
  following_list = following_filter.qs
  if request.method == 'POST':
    following_id = request.POST.get('following_id')
    following_user = User.objects.get(id=following_id)
    user.instagramuser.following.remove(following_user)
    following_user.instagramuser.follower.remove(user)
    # return redirect('following', user.id)
    return redirect('following')
  context = {'list':following_list, 'following_filter':following_filter}
  return render(request, 'igclone/following.html', context)



@login_required(login_url='login_register:login')
def followersPage(request, pk):
  user = request.user
  follower_list = user.instagramuser.follower.all()
  follower_filter = FollowerFilter(request.GET, queryset=follower_list)
  follower_list = follower_filter.qs
  if request.method == 'POST':

igclone/templates/igclone/edit_profile.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Edit Profile{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home, User Page, and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'user_page' request.user.id %}">
          <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <!-- Main Wrapper -->
  <div class="edit_wrapper">

    <div class="container flex">
      
      <!-- User's Data -->
      <section class="user_info flex">
        <img src="{{request.user.instagramuser.profile_pic.url}}" class="profile_pic">
        <div class="user_data grid">

          <div class="full_name">{{ request.user.first_name }}</div>
          <a class="btn profile_btn" href="{% url 'user_page' request.user.id %}">Profile</a>
          <div class="username">{{ request.user.username }}</div>
          <div></div>
          <form action="" method="POST">

            <!-- Url for an API call in edit_profile.js -->
            <input type="hidden" id="edit_profile" value="{% url 'edit_profile' request.user.id %}">

            <!-- User's Id for an API call in edit_profile.js -->
            <input type="hidden" id="user_id" value="{{request.user.id}}">

            <div id="switch_theme" class="btn switch_btn">Switch Theme</div>
          </form>
          
        </div>
      </section>

      <!-- Update user's information -->
      <section class="card">
        <form method="POST" action="" enctype="multipart/form-data">
          <input type="hidden" value="update" name="update" id="update">
          {% csrf_token %}
          <div class="edit_form">Profile Image {{ pic_form.profile_pic }}
          <label class="btn" for="id_profile_pic"> + Choose Photo</label></div>
          <div class="edit_form">Username {{form.username}}</div>
          <div class="edit_form">Full Name {{form.first_name}}</div>
          <input type="submit" class="btn update_btn" value="Update Information">
        </form>
      </section>

      <br>
      <a class="btn del_btn" href="{% url 'delete_profile' request.user.id %}">Delete Profile</a>
    </div>
  </div>

  <script type="text/javascript" src="{% static 'js/edit_profil.js' %}"></script>


{% endblock content %}

igclone/templates/igclone/follow_user.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}{{host_user.username}}{% endblock title %}
{% block content %}

  <!-- Navbar -->
    <div class="navbar">
      <div class="container flex">
        <!-- Instagram Logo -->
        <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
        <!-- Home, User Page, and Logout links -->
        <nav>
          <ul>
            <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
            <li><a href="{% url 'user_page' request.user.id %}">
            <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
            <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
          </ul>
        </nav>
      </div>
    </div>

  <!-- Main Wrapper -->
  <div class="follow_wrapper">

    <div class="container flex">
      
      <!-- User's Data -->
      <section class="user_info flex">
        <img src="{{host_user.instagramuser.profile_pic.url}}" class="profile_pic">
        <div class="user_data grid">
          <div class="full_name">{{ host_user.first_name }}</div>

          <form method="POST" action="{% url 'follow_user' host_user.id %}">
            {% csrf_token %}
            {% if host_user not in guest_user.instagramuser.following.all %}
              <input type="submit" class="btn" value="Follow">
            {% else %}
              <button type="submit" class="btn follow_button"><img class="follow_pic" src="{% static 'images/followers_icon.png' %}" alt=""></button>
            {% endif %}
            
          </form>

          <div class="posts">{{ num_users_photos }} post{{num_users_photos|pluralize}}</div>

          <div class="num_followers"><a href="{% url 'followerList' host_user.id %}">{{ num_followers }} follower{{num_followers|pluralize}}</a></div>
          
          <div class="num_following"><a href="{% url 'followingList' host_user.id %}">{{ num_following }} following</a></div>

          <div class="username">{{ host_user.username }}</div>
          
        </div>
      </section>

      <!-- User's Photos -->
      <section class="user_photos">
        <div class="grid">
          {% for users_photo in users_photos %}
            <a href="{% url 'publication' host_user.id users_photo.id %}" class="view_com"><img class="u_photo"
            src="{{ users_photo.image.url }}" alt=""></a>
       
          {% endfor %}
        </div>
      </section>

    </div>
  </div>

{% endblock content %}

igclone/templates/igclone/follower.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Followers{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home, User Page, and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'user_page' request.user.id %}">
          <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="following_wrapper">
    <div class="container flex">
      <section class="flex">
        <form class="following_form" action="" method="GET">
          {{follower_filter.form}}
          <input type="submit" class="btn search_btn" value="Search">
        </form>
      </section>
      <section class="wrapper_user flex">
        {% for follower in list %}
          <div class="phf_wrapper flex">

            <div class="flex">
             <a href="{% url 'follow_user' follower.id %}"><img class="fu_photo" src="{{follower.instagramuser.profile_pic.url}}" alt=""></a>
              <div class="name_wrapper">
                <p>{{follower.first_name}}</p>
                <p>{{follower.username}}</p>
              </div>
            </div>

            <div class="form_wrapper">
              <form action="" method="POST">
                {% csrf_token %}
                {% if follower not in request.user.instagramuser.following.all %}
                  <input type="hidden" value="{{follower.id}}" name="follower_id">
                  <input type="hidden" value="follow_back" name="follow_back">
                  <input class="btn" type="submit" value="follow back">
                {% endif %}
              </form>

              <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{follower.id}}" name="follower_id">
                <input class="btn remove_btn" type="submit" value="remove">
              </form>
            </div>
          </div>
        {% endfor %}
      </section>
    </div>
  </div>

{% endblock content %}

igclone/templates/igclone/follower_list.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Followers{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home, User Page, and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'user_page' request.user.id %}">
          <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="following_wrapper">
    <div class="container flex">
      <section class="flex">
        <form class="following_form" action="" method="GET">
          {{follower_filter.form}}
          <input type="submit" class="btn search_btn" value="Search">
        </form>
      </section>
      <section class="wrapper_user flex">
        {% for follower in list %}
          <div class="phf_wrapper flex">

            <div class="flex">
             <a href="{% url 'follow_user' follower.id %}"><img class="fu_photo" src="{{follower.instagramuser.profile_pic.url}}" alt=""></a>
              <div class="name_wrapper">
                <p>{{follower.first_name}}</p>
                <p>{{follower.username}}</p>
              </div>
            </div>
            
          </div>
        {% endfor %}
      </section>
    </div>
  </div>

{% endblock content %}

igclone/templates/igclone/following.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Following{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home, User Page, and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'user_page' request.user.id %}">
          <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="following_wrapper">
    <div class="container flex">
      <section class="flex">
        <form class="following_form" action="" method="GET">
          {{following_filter.form}}
          <input type="submit" class="btn search_btn" value="Search">
        </form>
      </section>
      <section class="wrapper_user flex">
        {% for following in list %}
          <div class="phf_wrapper flex">
            <div class="flex">
              <a href="{% url 'follow_user' following.id %}"><img class="fu_photo" src="{{following.instagramuser.profile_pic.url}}" alt=""></a>
              <div class="name_wrapper">
                <p>{{following.first_name}}</p>
                <p>{{following.username}}</p>
              </div>
            </div>
            <form action="" method="POST">
              {% csrf_token %}
              <input type="hidden" value="{{following.id}}" name="following_id">
              <input class="btn" type="submit" value="unfollow">
            </form>              
          </div>
        {% endfor %}
      </section>
    </div>
  </div>

{% endblock content %}

igclone/templates/igclone/post_user.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}Post{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home, User Page, and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'user_page' request.user.id %}">
          <img class="user_icon" src="{{request.user.instagramuser.profile_pic.url}}" alt=""></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <!-- Post Wrapper -->
  <div class="post_wrapper">

    <div class="container flex">
      
      <section>
        <div class="card">
          <img class="post_img" src="{{post.image.url}}" alt="">
        </div>
      </section>

      <section>
        <br>
        <a class="btn profile_btn back_profile" href="{% url 'user_page' request.user.id %}">Profile</a>
        <div class="add_wrapper">
          <div class="card edit_card">
            <form method="POST" action="" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="edit_form">Change Photo {{form_post.image}}
              <label class="btn" for="id_image"> + Choose Photo</label></div>

              <div class="edit_form">Change Description {{form_post.description}}</div>

              <input type="submit" class="btn update_btn" value="Update Post">

            </form>
          </div>
        </div>
        <a class="btn profile_btn del_btn" href="{% url 'delete_post' post.id %}">Delete Post</a>
        <br>
        <br>
      </section>
      <br>
    </div>
  </div>


{% endblock content %}

igclone/templates/igclone/user_page.html
{% extends 'igclone/main.html' %}
{% load static %}
{% block title %}{{user.username}}{% endblock title %}
{% block content %}

  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <!-- Instagram Logo -->
      <a href="{% url 'home' %}"><div class="instagram_logo">Instagram</div></a>
      <!-- Home and Logout links -->
      <nav>
        <ul>
          <li><a href="{% url 'home' %}"><i class="fas fa-home fa-2x"></i></a></li>
          <li><a href="{% url 'login_register:logout' %}"><i class="fas fa-sign-out-alt fa-2x "></i></a></li>
        </ul>
      </nav>
    </div>
  </div>

  <!-- User Area -->

  <!-- Main Wrapper -->
  <div class="user_wrapper">

    <!-- Url for an API call in user_page.js -->
    <input type="hidden" id="user_page" value="{% url 'user_page' request.user.id %}">
    
    <div class="container flex">
      
      <!-- User's Data -->
      <section class="user_info flex">
        <a href="{% url 'edit_profile' request.user.id %}"><img src="{{user.instagramuser.profile_pic.url}}" class="profile_pic"></a> 
        <div class="user_data grid">
          <div class="full_name">{{ user.first_name }}</div>
          <a class="btn" href="{% url 'edit_profile' request.user.id %}">Edit Profile</a>
          <div class="posts">{{ num_user_photos }} post{{num_user_photos|pluralize}}</div>
          <div class="num_followers"><a href="{% url 'followers' request.user.id %}">{{ num_followers }} follower{{num_followers|pluralize}}</a></div>
          <div class="num_following"><a href="{% url 'following' request.user.id %}">{{ num_following }} following</a></div> 
          <div class="username">{{ user.username }}</div>
          <a class="btn" href="{% url 'add_photo' %}">Add Photo</a>
        </div>
      </section>

      <!-- User's Photos -->
      <section class="user_photos">
        <div class="grid">
          {% for user_attribute in user_attributes %}
            <a href="{% url 'post' user_attribute.id %}"><img class="u_photo"
            src="{{ user_attribute.image.url }}" alt=""></a>
          {% endfor %}
        </div>
      </section>

    </div>
  </div>

  <script type="text/javascript" src="{% static 'js/user.js' %}"></script>


{% endblock content %}